#+ endpoint: http://fuseki:3030/reflexion/query
#+ endpoint_in_url: False
#+ method: GET
#+ summary: Retrieves scan qualities that appear in the guidelines and are part of the model (non body-part specific).

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX refl: <http://reflexion/acr#>
PREFIX re: <http://www.w3.org/2000/10/swap/reason#>
PREFIX ref: <http://purl.org/vocab/relationship/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?label
WHERE {
  ?specquality rdfs:subClassOf+ refl:recommended-quality.  
  FILTER NOT EXISTS {
    ?specquality rdfs:subClassOf+ [rdfs:subClassOf+ refl:recommended-quality].
  }
  ?specquality rdfs:label ?label.
}


