#+ endpoint: http://fuseki:3030/reflexion/query
#+ method: GET
#+ summary: Retrieves scan type for MR scan data.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX refl: <http://reflexion/acr#>
PREFIX re: <http://www.w3.org/2000/10/swap/reason#>
PREFIX ref: <http://purl.org/vocab/relationship/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?scan ?scantype
WHERE {
 ?scan a refl:MR-scan-result.
 OPTIONAL {
    ?scantype rdfs:subClassOf+ refl:MR-scan-result.
 	?scan a ?scantype.
  }
}
